language: ruby

dist: trusty

rvm:
  - 2.3.0
  - 2.3.6
  - 2.3.7
  - 2.4.0
  - 2.5.0

install: bundle install --jobs=3 --deployment --without development

script: bundle exec ruby test/test.rb

git:
  depth: 3
